DECLARE
Vfirst_name EMPLOYEES.FIRST_NAME%TYPE;
Vlaste_name EMPLOYEES.LAST_NAME%TYPE;
Vsalary EMPLOYEES.SALARY%TYPE;
BEGIN
INSERT INTO EMPLOYEES
(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES
(EMPLOYEES_SEQ.NEXTVAL, 'VINICIUS', 'MATHEUS', 'VINICIUSMATHEUS@GMAIL.COM','45 99983459', SYSDATE, 'IT_PROG', 15000, 0.4, 103, 60);
 COMMIT;
END;